-- COMPLETE DATABASE SETUP & FIX
-- This script combines all previous setups, fixes, and security improvements into one file.
-- Run this in Supabase SQL Editor to fully initialize or repair your database.

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES

-- Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL,
  images TEXT[] NOT NULL DEFAULT '{}',
  description TEXT,
  category TEXT,
  specs JSONB,
  collections TEXT[] DEFAULT '{}',
  is_new BOOLEAN DEFAULT false,
  story TEXT,
  technical_specs TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT,
  customer_address TEXT,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Admin Whitelist Table
CREATE TABLE IF NOT EXISTS admin_whitelist (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_whitelist ENABLE ROW LEVEL SECURITY;

-- 4. CLEANUP OLD POLICIES (To avoid conflicts)
DROP POLICY IF EXISTS "Public products are viewable by everyone" ON products;
DROP POLICY IF EXISTS "Admins can modify products" ON products;
DROP POLICY IF EXISTS "Whitelisted admins can modify products" ON products;
DROP POLICY IF EXISTS "Public can create orders" ON orders;
DROP POLICY IF EXISTS "Admins can view orders" ON orders;
DROP POLICY IF EXISTS "Admins can update orders" ON orders;
DROP POLICY IF EXISTS "Whitelisted admins can view orders" ON orders;
DROP POLICY IF EXISTS "Whitelisted admins can update orders" ON orders;
DROP POLICY IF EXISTS "Authenticated users can read whitelist" ON admin_whitelist;

-- 5. DEFINE SECURE POLICIES

-- Products: Everyone can see products (Force Public Access)
CREATE POLICY "Public products are viewable by everyone" 
ON products FOR SELECT 
TO public
USING (true);

-- Products: Only Whitelisted Admins can modify (Insert/Update/Delete)
CREATE POLICY "Whitelisted admins can modify products" 
ON products FOR ALL 
USING (
  auth.role() = 'authenticated' AND 
  (auth.jwt() ->> 'email') IN (SELECT email FROM admin_whitelist)
);

-- Orders: Everyone can create orders (Checkout)
CREATE POLICY "Public can create orders" 
ON orders FOR INSERT 
WITH CHECK (true);

-- Orders: Only Whitelisted Admins can view orders
CREATE POLICY "Whitelisted admins can view orders" 
ON orders FOR SELECT 
USING (
  auth.role() = 'authenticated' AND 
  (auth.jwt() ->> 'email') IN (SELECT email FROM admin_whitelist)
);

-- Orders: Only Whitelisted Admins can update orders (e.g. status)
CREATE POLICY "Whitelisted admins can update orders" 
ON orders FOR UPDATE 
USING (
  auth.role() = 'authenticated' AND 
  (auth.jwt() ->> 'email') IN (SELECT email FROM admin_whitelist)
);

-- Admin Whitelist: Authenticated users can read (to check if they are admin)
CREATE POLICY "Authenticated users can read whitelist" 
ON admin_whitelist FOR SELECT 
USING (auth.role() = 'authenticated');

-- 6. GRANT PERMISSIONS (Fix for 'anon' access issues)
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO authenticated;

-- 7. SEED DATA

-- Add Admin User
INSERT INTO admin_whitelist (email) 
VALUES ('iiih10923@gmail.com')
ON CONFLICT (email) DO NOTHING;

-- Add Initial Products (Only if they don't exist)
INSERT INTO products (name, price, image, images, description, category, specs, collections, is_new, story, technical_specs)
SELECT 
  'Obsidian Bomber', 
  2400, 
  'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop', 
  ARRAY['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop'],
  'A masterclass in tactical luxury. The Obsidian Bomber is crafted from a rare blend of Kevlar and reinforced silk.', 
  'Outerwear', 
  '{"material": "Kevlar/Silk", "weight": "1.2kg", "resistance": "Wind/Water"}', 
  ARRAY['Full Collection'], 
  false, 
  'A masterclass in tactical luxury...', 
  ARRAY['Kevlar/Silk', '1.2kg', 'Wind/Water']
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Obsidian Bomber');

INSERT INTO products (name, price, image, description, category, specs, collections, is_new, story, technical_specs)
SELECT 
  'SOLTAN X1 CHRONOGRAPH', 
  125000, 
  'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=2080&auto=format&fit=crop', 
  'A masterpiece of engineering and design. The X1 Chronograph represents the pinnacle of luxury timekeeping.', 
  'Watches', 
  '{"Movement": "Swiss Automatic", "Case": "Titanium", "Water Resistance": "100m"}', 
  ARRAY['Top Sellers', 'New Arrivals'], 
  true, 
  'Born from a desire to push boundaries...', 
  ARRAY['Diameter: 42mm', 'Power Reserve: 72h']
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'SOLTAN X1 CHRONOGRAPH');

INSERT INTO products (name, price, image, description, category, specs, collections, is_new, story, technical_specs)
SELECT 
  'ROYAL OAK CUFFLINKS', 
  4500, 
  'https://images.unsplash.com/photo-1617038224531-16d42b468579?q=80&w=2070&auto=format&fit=crop', 
  'Elegant cufflinks crafted from 18k gold. The perfect accessory for the modern gentleman.', 
  'Accessories', 
  '{"Material": "18k Gold", "Weight": "15g"}', 
  ARRAY['Accessories'], 
  false, 
  'Inspired by royal traditions...', 
  ARRAY['Dimensions: 15mm x 15mm']
WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'ROYAL OAK CUFFLINKS');
